# **Introdução à Modelagem Econômica e Ciência de Dados (2022).**

# *Primeiro Trabalho - a ser devolvido ate o dia 21/10/2022.*

## **Exercício 1.** (15 pontos) Corrigindo um teste de múltipla escolha.

Escreva um código que calcule a nota de um teste de múltipla escolha contendo 5 questões (cada uma valendo 20 pontos). Cada questão possui 5 alternativas, nomeadas "a", "b", "c", "d" e "e". A resposta correta da primeira questão é "b", da segunda questão é "e", da terceira questão é "c", da quarta questão é "a" e da quinta questão é "d". Entre com a resposta de cada uma das questões e a seguir apresente a pontuação. O console deve imprimir a seguinte informação: 

`Entre com a resposta da questão 1: ___`

`Entre com a resposta da questão 2: ___`

`Entre com a resposta da questão 3: ___`

`Entre com a resposta da questão 4: ___`

`Entre com a resposta da questão 5: ___`

`O aluno fez ___ pontos.`

**Por exemplo:** Suponha que um aluno tenha respondido assim: primeira questão "a", segunda questão "e", terceira questão "d", quarta questão "b" e quinta questão "d". Neste caso o console irá imprimir:

`Entre com a resposta da questão 1: a`

`Entre com a resposta da questão 2: e`

`Entre com a resposta da questão 3: d`

`Entre com a resposta da questão 4: b`

`Entre com a resposta da questão 5: d`

`O aluno fez 40 pontos.`

In [15]:
# Entra o código

x = input('Entre com a resposta da questão 1: ')
y = input('Entre com a resposta da questão 2: ')
z = input('Entre com a resposta da questão 3: ')
w = input('Entre com a resposta da questão 4: ')
p = input('Entre com a resposta da questão 5: ')

dic = {'b': x, 'e': y, 'c': z, 'a': w, 'd': p}

note = 0

for row, line in dic.items():     
    if row == line:
        note += 20

print(f'O Aluno fez: {note}')

O Aluno fez: 0


---

## **Exercício 2.** (15 pontos) Construindo uma função que calcula o fatorial de um número.

Escreva um código que define uma função que permite calcular o fatorial de um número. A seguir pergunte um número para calcular seu fatorial. O console deve imprimir a seguinte informação:

`Entre um número: __X__`

`O fatorial de __X__ é __Y__.`

**Por exemplo:** Suponha que o número inserido seja `3`. Neste caso o console irá imprimir:

`Entre um número: 3`

`O fatorial de 3 é 6.`


In [31]:
# Entra o código
def fatorial(x): #Criando uma def que irá fazer o calculo de fatorial quando x for maior que 1
    fatorial = 1
    while x > 1:
        fatorial *= x # equivale a fatorial = fatorial * x
        x += 1
    return fatorial #fechando a def (está nominada para ser usada abaixo)

x = int(float(input("Entre um número: ")))  # A fatorial se aplica apenas a num inteiros >= 1

while  (int(x) < 0) :  #Usando um condicional para o input acima
        print("\n>>> Erro.")  #Apresentará erro se o valor for < 0
        break #stopa o loop que foi criado, porém está repetindo um valor que não era (no caso sempre que for menor que 1, repetira o 1)
print(f"\nO fatorial de {x} é {fatorial(x)}.") 



O fatorial de 1 é 1.


## **Exercício 3.** (15 pontos) Construindo uma função que calcula a sequencia de N números *Fibonacci*.

Escreva um código que define uma função que permite obter uma sequencia de Fibonacci com N números. A seguir pergunte um número N de elementos da sequencia de Fibonacci. O console deve imprimir a seguinte informação:

`Entre o número de elementos da sequencia de Fibonacci: __N__`

`A sequencia dos _N_ primeiros numeros de Fibonacci é: __F__.`

**Por exemplo:** Suponha que o número inserido seja `4`. Neste caso o console irá imprimir:

`Entre o número de elementos da sequencia de Fibonacci: 4`

`A sequencia dos _N_ primeiros numeros de Fibonacci é: 1, 1, 2, 3.`


In [44]:
# Sequencia de Fibonnacci

fib = int(input("Entre o número de elementos da sequência de Fibonacci: "))
x, y = 0, 1
count = 0   #Indexador  (iniciará sempre do 0)


if fib <= 0:
    print('Por favor entre com um valor positivo int')
elif fib == 1:
    print('A sequencia de Fibonnacci é',fib,':')
    print(x)
else:
    print('A sequencia de Fibonnacci é:')
    while count < fib:
        print(x)
        z = x + y
        x = y
        y = z
        count += 1

A sequencia de Fibonnacci é:
0
1
1
2
3
5
8
13
21
34


## **Exercício 4.** (15 pontos) Saldo em carteira de fundos de investimentos.

Escreva um código, utilizando Numpy, que permite avaliar o saldo em carteira de fundos de investimentos de dois investidores. Em um certo dia, "Paulo" e "Cesar" possuiam, em suas respectivas carteiras, cotas de fundos de investimentos com as seguintes posições:

|Investidor|Renda Fixa|Ações|Multimercado|Cryptomoedas
|--|--|--|--|--|
|Paulo | 6| 3 |1 |0|
|Cesar | 9| 0|0|0.5|

O valor das cotas desses fundos ao final deste certo dia é o que segue: \$ 20.00 para o fundo de renda fixa, \$ 15.00 para o fundo de ações, \$ 18.00 para o fundo multimercado e \$ 6.00 para o fundo de cryptomoedas.

i. Utilizando Numpy, monte a matriz com as posições das carteiras de fundos de investimentos de "Paulo" e de "Cesar".

In [51]:
# Entra o código
import numpy as np #importando a lib 
#transformando as informações do quadro em matriz
x = np.array([[6,3,1,0],[9,0,0,0.5]])

print(x)


[[6.  3.  1.  0. ]
 [9.  0.  0.  0.5]]


ii. Utilizando Numpy, monte uma matriz de valor das cotas de fechamento dos fundos (esta matriz deve possuir 4 linhas e 1 coluna).

In [52]:
# Entra o código
y = np.array([[20],[15],[18],[6]])

print(y)

[[20]
 [15]
 [18]
 [ 6]]


iii. Utlizando Numpy, encontre o valor da carteira de fundos de investimentos de cada investidor.

In [54]:
# Entra o código
z = x.dot(y)
print(z)

[[183.]
 [183.]]


Apresente no console a informação da seguinte forma:

`O valor da carteira de fundos de investimentos é de $ 183.00 para o Paulo e de $ 183.00 para o Cesar.`

In [56]:
# Entra o código
print(f'O valor da carteira de fundos de investimentos é de ${z[0][0]} para o Paulo e de ${z[1][0]} para o Cesar.')

O valor da carteira de fundos de investimentos é de $183.0 para o Paulo e de $183.0 para o Cesar.


## **Exercício 5.** (15 pontos) Alocação dos recursos em investimentos.

Escreva um código, utilizando Numpy, que permita determinar como um gestor deverá alocar os recursos entre fundos de investimentos. Suponha que este gestor tenha feito uma minunciosa análise e tenha concluido que dispõe de 3 fundos para poder alocar os recursos. O fundo A é o que apresenta risco mais elevado, o fundo B apresenta um risco intermediário e o fundo C apresenta baixo risco. De acordo com as projeções deste gestor, os retornos esperados para estes fundos são de: 20% a.a para o fundo A, 12.5% a.a. para o fundo B e 6% a.a. para o fundo C. Em sua análise para a gestão dos recursos o gestor decidiu que o montante que irá investir no fundo C deverá corresponder à soma do montante investido nos fundos A e B. Este gestor dispõe de \$ 100.00 para investir nos fundos A, B e C e o objetivo é o de alcançar um retorno de \$ 10.00. 

O console deverá irá imprimir:

`Montantes a serem alocados: fundo A = $ 10.00, fundo B = $ 40.00 e fundo C = $ 50.00.`

**Breve discussão sobre a estrutura do problema:** 

Sejam $x_A$, $x_B$ e $x_C$, respectivamente, os montantes a serem alocados nos fundos A, B e C. 

A partir do enunciado, temos que as restrições do problema são as seguintes:

$$ \left\{\begin{matrix}
0.2 x_A & + & 0.125 x_B & + & 0.06 x_C & = & 10 \\
-x_A & - & x_B & + & x_C & = &0 \\
x_A & + & x_B & + & x_C & = & 100
\end{matrix}\right |$$

Ou, de forma matricial, $$ Ax = B $$ onde:

$$ A = 
\begin{bmatrix} 
0.2 & 0.125 & 0.06 \\
 -1 & -1 & 1 \\
  1 & 1 & 1 
\end{bmatrix} $$, 
$$ x =
\begin{bmatrix} 
x_A \\
x_B \\
x_C 
\end{bmatrix} $$ 
e 
$$ B =
\begin{bmatrix} 
10 \\
0 \\
100 
\end{bmatrix} $$

Cuja solução será dada por: $$ x = A^{-1} B $$


In [37]:
# Entra o código
import numpy as np

x = np.array(
    [
        [0.2, 0.125, 0.06], 
        [-1, -1, 1], 
        [1, 1, 1]]
    )

y = np.array( 
    [10, 0, 100]
)

w = np.linalg.inv(x).dot(y)
print(w)

#Função criada apenas para dividir a matriz acima e a impressão
def linha():
    print('_'*30)

linha()

#Função criada para dar espaço e deixar mais "bonito o output"
def space():
    print(' '*30)

space()

print(f'Montantes a serem alocados: fundo A = ${round(w[0])}, fundo B = ${w[1]} e fundo C = ${w[2]}')


[10. 40. 50.]
______________________________
                              
Montantes a serem alocados: fundo A = $10, fundo B = $40.0 e fundo C = $50.0


## **Exercício 6.** (15 pontos) Problema do consumidor.

Considere uma função de utilidade em relação a abacates (A) e barras de chocolate (B).

$$ U(A,B)=−(A−20)^2 −2(B−1)^2$$

Para calcular numericamente o máximo (que você provavelmente pode ver através da inspeção), deve-se resolver diretamente o problema de maximização restrita.

1. Encontre a cesta ótima quando $W = 10,\text{ }p_A = 1\text{, and }p_B = 2$.

2. Qual seria a cesta ótima se a renda passasse a ser de $W = 50$?

3. Qual seria a cesta ótima se a renda passasse a ser de $W = 150$?

In [ ]:
# Entra o código

## **Exercício 7.** (10 pontos) Problema livre de seu interesse.

Enuncie um problema de seu interesse e escreva um código que permita encontrar a solução. 

In [59]:
# Entra o código

# Importando a Lib
import random


# Criando o corpo do jogo
def jogar():
    print("*********************************")
    print("Bem vindo ao jogo de Adivinhação!")
    print("*********************************")

# Escolhendo um n° no espaço amostral selecionado
    numero_secreto = random.randrange(1,51)
    total_de_tentativas = 0
    pontos = 1000


# Criando uma interação para a escolher o numero de tentativas
    print("Qual nível de dificuldade?")
    print("(1) Fácil (2) Médio (3) Difícil")

# Input para passar a condicional seguinte e assim selecionar o modo de jogo
    nivel = int(input("Defina o nível: "))

# Definindo os modos e as tentativas
    if(nivel == 1):
        total_de_tentativas = 20
    elif(nivel == 2):
        total_de_tentativas = 10
    else:
        total_de_tentativas = 5


# Corpo do loop que irá repassar a cada tentativa e informar se o jogador acertou ou errou, mostrando tb se o n° inputado está no espaço amostral
    for rodada in range(1, total_de_tentativas + 1):
        print("Tentativa {} de {}".format(rodada, total_de_tentativas))
        chute_str = input("Digite um número entre 1 e 100: ")
        print("Você digitou " , chute_str)
        chute = int(chute_str)
        if(chute < 1 or chute > 100):
            print("Você deve digitar um número entre 1 e 100!")
            continue

        # Operação logica para saber dica dicas e saber se está certo 
        acertou = chute == numero_secreto
        maior   = chute > numero_secreto
        menor   = chute < numero_secreto

        # Condicional para informações mostradas nos inputs
        if(acertou):
            print("Você acertou e fez {} pontos!".format(pontos))
            break   #Sempre importante colocar o break para não virar um loop infinito não queremos isso.
        else: 
            if(maior):
                print("Você errou! O seu chute foi maior do que o número secreto.")
            elif(menor):
                print("Você errou! O seu chute foi menor do que o número secreto.")
            pontos_perdidos = abs(numero_secreto - chute)
            pontos = pontos - pontos_perdidos
    print("Fim do jogo")


if __name__ == "__main__":        #finalizando a iteração da função.
    jogar()

*********************************
Bem vindo ao jogo de Adivinhação!
*********************************
Qual nível de dificuldade?
(1) Fácil (2) Médio (3) Difícil
Tentativa 1 de 20
Você digitou  14
Você errou! O seu chute foi maior do que o número secreto.
Tentativa 2 de 20
Você digitou  12
Você errou! O seu chute foi maior do que o número secreto.
Tentativa 3 de 20
Você digitou  1
Você errou! O seu chute foi menor do que o número secreto.
Tentativa 4 de 20
Você digitou  25
Você errou! O seu chute foi maior do que o número secreto.
Tentativa 5 de 20
Você digitou  10
Você errou! O seu chute foi maior do que o número secreto.
Tentativa 6 de 20
Você digitou  12
Você errou! O seu chute foi maior do que o número secreto.
Tentativa 7 de 20
Você digitou  4315
Você deve digitar um número entre 1 e 100!
Tentativa 8 de 20
Você digitou  


ValueError: invalid literal for int() with base 10: ''